spring:
  application:
    name: category-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: azizjon
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
#  servlet:
#    context-path: /category-service
  port: 8000