spring:
  application:
    name: word-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: azizjon
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /word-service
  port: 8030